// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msrutrvanmhqpewmhddd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcnV0cnZhbm1ocXBld21oZGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NzUwMTUsImV4cCI6MjA4NjE1MTAxNX0.n7Sm8TdrQLzSLrUuTE2vf0YZjCIi_AQKld4_BSLUEis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
